Englandpath : './Data/England_Covid.csv'
EMidlandspath : './Data/England_East_Midlands_Covid.csv'
Eastpath : './Data/England_East_of_England_Covid.csv'
Londonpath : './Data/England_London_Covid.csv'
NorthWestpath : './Data/England_North_West_Covid.csv'
SouthWestpath : './Data/England_South_West_Covid.csv'
Y&Hpath : './Data/England_Yorkshire_and_The_Humber_Covid.csv'
NIrelandpath : './Data/Northern Ireland_Covid.csv'
Scotlandpath : './Data/Scotland_Covid.csv'
Walespath : './Data/Wales_Covid.csv'
poppath : './Data/ukpop.xls'
UK_geojson : './Data/Regions_(December_2021)_EN_BFC.geojson'
